#!/usr/bin/env bash
#
# fix-etcd-3.5-cluster.sh
#
# One-time migration / fix script to:
#   - Replace etcd 3.6.x with 3.5.x (for Patroni v2 API)
#   - Reset etcd data dir
#   - Configure a consistent 3-node cluster and systemd unit
#
# DANGER: This WILL DELETE all etcd data on this node.
# Run on all three nodes when you are ready to bootstrap
# a fresh 3.5.x etcd cluster.
#
# Usage (for your environment):
#   # node1
#   sudo bash fix-etcd-3.5-cluster.sh node1 172.16.15.36 \
#     "node1=http://172.16.15.36:2380,node2=http://172.16.15.37:2380,node3=http://172.16.15.38:2380" \
#     /tmp/etcd-v3.5.15-linux-amd64.tar.gz
#
#   # node2
#   sudo bash fix-etcd-3.5-cluster.sh node2 172.16.15.37 \
#     "node1=http://172.16.15.36:2380,node2=http://172.16.15.37:2380,node3=http://172.16.15.38:2380" \
#     /tmp/etcd-v3.5.15-linux-amd64.tar.gz
#
#   # node3
#   sudo bash fix-etcd-3.5-cluster.sh node3 172.16.15.38 \
#     "node1=http://172.16.15.36:2380,node2=http://172.16.15.37:2380,node3=http://172.16.15.38:2380" \
#     /tmp/etcd-v3.5.15-linux-amd64.tar.gz
#
# Arguments:
#   $1 = NODE_NAME        (e.g. node1)
#   $2 = NODE_IP          (e.g. 172.16.15.36)
#   $3 = INITIAL_CLUSTER  (full string for all nodes)
#   $4 = ETCD_TARBALL     (path to etcd-v3.5.x-linux-amd64.tar.gz)

set -euo pipefail

ETCD_VERSION_DEFAULT="3.5.15"
INSTALL_DIR="/usr/local/bin"
ETCD_ENV_FILE="/etc/etcd/etcd.conf"
ETCD_SERVICE_FILE="/etc/systemd/system/etcd.service"
ETCD_SERVICE_DROPIN_DIR="/etc/systemd/system/etcd.service.d"
ETCD_DATA_DIR_DEFAULT="/var/lib/etcd"

log()  { echo "[INFO] $*"; }
warn() { echo "[WARN] $*" >&2; }
fail() { echo "[FAIL] $*" >&2; exit 1; }

if [[ $EUID -ne 0 ]]; then
  fail "Must run as root (use sudo)."
fi

NODE_NAME="${1:-}"
NODE_IP="${2:-}"
INITIAL_CLUSTER="${3:-}"
ETCD_TARBALL="${4:-}"

if [[ -z "$NODE_NAME" || -z "$NODE_IP" || -z "$INITIAL_CLUSTER" ]]; then
  cat >&2 <<EOF
Usage:
  sudo bash $0 NODE_NAME NODE_IP INITIAL_CLUSTER [/path/to/etcd-v3.5.x-linux-amd64.tar.gz]

Example (your case):
  sudo bash $0 node1 172.16.15.36 \
    "node1=http://172.16.15.36:2380,node2=http://172.16.15.37:2380,node3=http://172.16.15.38:2380" \
    /tmp/etcd-v3.5.15-linux-amd64.tar.gz
EOF
  exit 1
fi

if [[ -z "$ETCD_TARBALL" ]]; then
  # Try some defaults if not given
  ETCD_TARBALL="/tmp/etcd-v${ETCD_VERSION_DEFAULT}-linux-amd64.tar.gz"
fi

if [[ ! -f "$ETCD_TARBALL" ]]; then
  fail "etcd tarball not found at: $ETCD_TARBALL"
fi

log "Node name        : $NODE_NAME"
log "Node IP          : $NODE_IP"
log "Initial cluster  : $INITIAL_CLUSTER"
log "etcd tarball     : $ETCD_TARBALL"

# Stop etcd service if running
log "Stopping etcd service (if running)..."
systemctl stop etcd 2>/dev/null || true

# Install / replace etcd with 3.5.x from tarball if needed
need_install=true
if command -v etcd >/dev/null 2>&1; then
  v_out="$(etcd --version 2>/dev/null || true)"
  if echo "$v_out" | grep -q "etcd Version: 3.5."; then
    log "Existing etcd is already 3.5.x:"
    echo "$v_out"
    need_install=false
  else
    warn "Existing etcd version is not 3.5.x:"
    echo "$v_out"
  fi
else
  warn "etcd binary not found in PATH; will install to $INSTALL_DIR"
fi

if $need_install; then
  log "Installing etcd 3.5.x from tarball..."
  tmpdir="$(mktemp -d)"
  tar -xzf "$ETCD_TARBALL" -C "$tmpdir"
  subdir="$(find "$tmpdir" -maxdepth 1 -type d -name "etcd-v*" | head -1 || true)"
  if [[ -z "$subdir" || ! -f "$subdir/etcd" ]]; then
    rm -rf "$tmpdir"
    fail "Tarball layout unexpected (no etcd-v* dir or etcd binary)."
  fi
  mkdir -p "$INSTALL_DIR"
  cp -f "$subdir/etcd" "$subdir/etcdctl" "$INSTALL_DIR/"
  chmod 755 "$INSTALL_DIR/etcd" "$INSTALL_DIR/etcdctl"
  rm -rf "$tmpdir"
  log "etcd 3.5.x binaries installed to $INSTALL_DIR"
  log "New etcd version:"
  "$INSTALL_DIR/etcd" --version || true
fi

# Determine ETCD_DATA_DIR
ETCD_DATA_DIR="$ETCD_DATA_DIR_DEFAULT"
if [[ -f "$ETCD_ENV_FILE" ]]; then
  # Try to read existing value if present
  existing_data_dir_line="$(grep -E '^ETCD_DATA_DIR=' "$ETCD_ENV_FILE" || true)"
  if [[ -n "$existing_data_dir_line" ]]; then
    ETCD_DATA_DIR="$(echo "$existing_data_dir_line" | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//')"
  fi
fi

log "Using ETCD_DATA_DIR: $ETCD_DATA_DIR"
warn "THIS WILL DELETE ALL DATA under $ETCD_DATA_DIR on this node."
read -r -p "Continue? [y/N]: " ans
ans="${ans:-N}"
if [[ "$ans" != "y" && "$ans" != "Y" ]]; then
  fail "Aborted by user."
fi

log "Deleting etcd data dir: $ETCD_DATA_DIR"
rm -rf "$ETCD_DATA_DIR"
mkdir -p "$ETCD_DATA_DIR"

# Write fresh /etc/etcd/etcd.conf for this node
log "Writing $ETCD_ENV_FILE ..."
mkdir -p "$(dirname "$ETCD_ENV_FILE")"
cat >"$ETCD_ENV_FILE" <<EOF
# etcd for Patroni DCS (auto-generated by fix-etcd-3.5-cluster.sh)
ETCD_NAME=${NODE_NAME}
ETCD_DATA_DIR="${ETCD_DATA_DIR}"
ETCD_LISTEN_CLIENT_URLS="http://${NODE_IP}:2379"
ETCD_LISTEN_PEER_URLS="http://${NODE_IP}:2380"
ETCD_INITIAL_ADVERTISE_CLIENT_URLS="http://${NODE_IP}:2379"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://${NODE_IP}:2380"
ETCD_ADVERTISE_CLIENT_URLS="http://${NODE_IP}:2379"
ETCD_INITIAL_CLUSTER="${INITIAL_CLUSTER}"
ETCD_INITIAL_CLUSTER_TOKEN="pg-ha-etcd"
ETCD_INITIAL_CLUSTER_STATE="new"
EOF

# Ensure systemd unit uses /usr/local/bin/etcd and env file
log "Ensuring systemd unit at $ETCD_SERVICE_FILE ..."
mkdir -p "$(dirname "$ETCD_SERVICE_FILE")"
if [[ ! -f "$ETCD_SERVICE_FILE" ]]; then
  cat >"$ETCD_SERVICE_FILE" <<EOF
[Unit]
Description=etcd - distributed key-value store for Patroni DCS
After=network.target

[Service]
Type=notify
EnvironmentFile=-${ETCD_ENV_FILE}
ExecStart=${INSTALL_DIR}/etcd
Restart=on-failure
RestartSec=10s
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF
fi

mkdir -p "$ETCD_SERVICE_DROPIN_DIR"
cat >"${ETCD_SERVICE_DROPIN_DIR}/environment.conf" <<EOF
[Service]
EnvironmentFile=${ETCD_ENV_FILE}
EOF

log "Reloading systemd daemon..."
systemctl daemon-reload

log "Enabling etcd service..."
systemctl enable etcd >/dev/null 2>&1 || true

log "Starting etcd service..."
if ! systemctl start etcd; then
  warn "etcd failed to start. Showing status:"
  systemctl status etcd -l || true
  warn "Check logs with: journalctl -xeu etcd.service"
  exit 1
fi

log "Waiting a few seconds for etcd to come up..."
sleep 3

log "Checking etcd /health..."
curl -s "http://127.0.0.1:2379/health" || true
echo

log "Checking etcd /v2/machines (v2 API for Patroni)..."
curl -s "http://127.0.0.1:2379/v2/machines" || true
echo

log "Done on this node. Repeat on the other nodes with their NODE_NAME and NODE_IP."
